cmd: "swift build"
name: "Flamingo"
sh: true,
#cwd: <current working directory for `cmd`>
#
# env:
#   VARIABLE1: "VALUE1"
#   VARIABLE2: "VALUE2"
# errorMatch:
#   - ^regexp1$
#   - ^regexp2$
# warningMatch:
#   - ^regexp1$
#   - ^regexp2$
# keymap: <keymap string>
# atomCommandName: namespace:command
# targets:
#   extraTargetName:
#       cmd: "<command to execute>"
#       args:
# **/
