os:
  - osx
  - linux
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./swiftlint.sh; fi
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
script:
  - . ~/.swiftenv/init
  - rm -rf Packages .build
  - swift build --fetch
  - swift build
  - swift test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swiftlint; fi
notifications:
  email: false
